/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.System;

import java.awt.event.ActionEvent;
import Client.ComClient;
import java.awt.event.ActionListener;
import java.io.IOException;

/**
 *
 * @author user
 */
public class ComputerActionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComputerActionFrame
     */
    public ComputerActionFrame() {
        initComponents();
        
        select.addActionListener((ActionEvent e) -> {
            dispose();
        });
        
        try {
            // BrokenComputer 객체 생성
            ComClient client = new ComClient();
            // 고장난 컴퓨터 ID 목록 가져오기
            String response = client.requestBrokenComputerList();
            client.close();
            
            StringBuilder sb = new StringBuilder();
            
            if (response.startsWith("SUCCESS|")) {
                String data = response.substring("SUCCESS|".length());
                String[] ids = data.split(",");
            
                // 각 컴퓨터 ID 문자열에 추가
                for (String id : ids) {
                    sb.append("컴퓨터 ID: ").append(id).append("\n");
                }
            } else if (response.startsWith("EMPTY|")) {
                sb.append("고장난 컴퓨터가 없습니다.");
            } else {
                sb.append("서버 오류: ").append(response);
            }
            comList.setText(sb.toString()); // JTextArea (comList)에 출력
        } catch (IOException e) {
            comList.setText("고장 컴퓨터 목록을 불러오는 중 오류 발생: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        select.setText("확인");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        jLabel1.setText("고장 컴퓨터 리스트");

        comList.setEditable(false);
        comList.setColumns(20);
        comList.setRows(5);
        jScrollPane1.setViewportView(comList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(select)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(select)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables
}